### ISSUE TITLE
Same labels for two different tables

### ISSUE THREAD

**Issue by JinchengHeRyan** [sunshineluyao/CSECON206_ProblemSet1#1]
Just a small issue. In `PS1.tex`, there are same labels for two different tables, in line ***320*** and ***338*** respectively. Though it does affect being compiled successfully, it may cause problem when referring table is needed and may refer to the wrong table.

**Comment by JinchengHeRyan** [comment]
Seems like being fixed in 3c46627e3f34d1901a27e60146c451a5d86b40e1, issue closed.

**Comment by sunshineluyao** [comment]
thanks
